### ISSUE TITLE
eValue undercalculates extrusion volume

### ISSUE THREAD

**Issue by jimgregory** [prahjister/Calibration-Generator#5]
Thanks for writing this.  I've modified it to create a command-line version so it's unnecessary to run Qt or open a web browser.

I have a question about calculating the extrusion volume.  The eValue function has a magic number of 1.25 in its divisor.  This cuts the extrusion volume by 20%.  

Was this intentional?  Doesn't it effect the test results? When I removed the 1.25 from the equation, my results came out looking more normal.  

Compensating for this by using 1.25 by the extrusion multiplier would give you false impression that 1.25x should be used for the final printer configuration.

**Comment by prahjister** [comment]
In this code, I added the 1.25 to over extrude slightly. At least that is what I was attempting. Additionally, I modified the formula from the StackExchange question because it appeared to be incorrect. I changed the multiplication to division for the multiplier. I may be wrong and this might be why some printers under extrude. I assumed that if eValueresult increases more filament will come out but I may be wrong.

I really appreciate your efforts. I will do some testing tonight

# Generate E Value  https://3dprinting.stackexchange.com/questions/10171/how-is-e-value-calculated-in-slic3r 

        def eValue ( extrusionLength ):

            diameterNozzle = float(ui.nozzleDiameter.text())
            heightLayer = float(ui.layerHeight.text())
            diameterFilament = float(ui.filamentDiameter.text())
            multiplierExtrusion = float(ui.extrusionMultiplier.text())

            area = (diameterNozzle - heightLayer) * heightLayer + 3.14159 * (heightLayer/2)**2
            eValueresult = (area * extrusionLength * 4)/(3.14159 * diameterFilament**2/multiplierExtrusion*1.25)
            return eValueresult

**Comment by prahjister** [comment]
You are absolutely right. Thank you so much. I have removed it. I can't believe I didn't catch this. I am in the process of updating.

To test I took a 10mm box into Cura and generated gcode for vase mode. Cura calls for about 8% more filament per 10mm length, per its gcode but cura may do that because of vase mode.

**Comment by jimgregory** [comment]
No problem, thanks for fixing it. :-)

I think the Stack Overflow formula is probably correct; i.e., the volume of the extruded material is directly proportional to the extrusion multiplier.  This would imply that for a fixed volume of extruded material, a higher extrusion multiplier would have a lower eValue.  That suggests the extrusion multiplier should be in the denominator of the eValue equation.

**Comment by prahjister** [comment]
Ohh yes and with the extrusion multiplier. I left that part of the formula the same. When I put in 1.1 I am expecting 10% more. I tested it and it lines up with Acura. Some reason its only 9% on both be linearly they line up.

**Comment by jimgregory** [comment]
The more I think about it, the more I think you're right about the extrusion multiplier.

I think the Stack Overflow equation should be:

     volume out = (volume in) / (extrusion multiplier)

If the extrusion multiplier > 1, then a higher volume in is needed to extrude an equivalent volume out.  If < 1, the volume in would be reduced.  That would match your equation and your results.
